name: polar-converter-dev

services:
  polar-converter:
    image: uebliche/base-java21
    working_dir: /workspace
    volumes:
      - ./:/workspace
      - gradle-cache:/gradle-cache
    environment:
      GRADLE_USER_HOME: /gradle-cache/polar-converter
      GRADLE_PROJECT_CACHE_DIR: /gradle-cache/polar-converter-project
      JAVA_TOOL_OPTIONS: ${JAVA_TOOL_OPTIONS:--Xms512M -Xmx1G -XX:+UseG1GC}
      GRADLE_OPTS: ${GRADLE_OPTS:--Dorg.gradle.jvmargs=-Xmx1G -Dorg.gradle.workers.max=2}
    command:
      - bash
      - -lc
      - |
        set -euo pipefail
        tmp=$(mktemp /workspace/gradlew-docker-XXXXXX)
        trap 'rm -f "$tmp"' EXIT
        tr -d '\r' < gradlew > "$tmp"
        chmod +x "$tmp"
        "$tmp" --gradle-user-home /gradle-cache/polar-converter --project-cache-dir /gradle-cache/polar-converter-project run --no-daemon
    ports:
      - "${HOST_PORT:-0}:25565"
    labels:
      net.uebliche.dockbridge.autoregister: "${DOCKBRIDGE_AUTOREGISTER:-true}"
      net.uebliche.dockbridge.server_name: "polar-converter"
      net.uebliche.dockbridge.server_port: "25565"
      net.uebliche.dockbridge.autojoin: "${DOCKBRIDGE_AUTOJOIN:-false}"

volumes:
  gradle-cache:
